---
- name: Upload Config | filebeat
  template:
    src: etc/filebeat/filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: staff
    mode: 0664
  notify: Restart Service | filebeat
  tags:
    - configuration
    - template-configuration
    - filebeat

- name: Upload SSL | filebeat
  template:
    src: etc/filebeat/ssl.crt
    dest: /etc/filebeat/ssl.crt
    owner: root
    group: root
    mode: 0600
  notify: Restart Service | filebeat
  when: filebeat_ssl_certificate is defined
  tags:
    - configuration
    - template-configuration
    - filebeat
